# Generated by Django 3.0.5 on 2021-01-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210124_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='document',
            field=models.FileField(upload_to='static/bird/'),
        ),
    ]
