# Generated by Django 3.0.5 on 2021-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210124_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='document',
            field=models.ImageField(upload_to='static/bird/'),
        ),
    ]
