# Generated by Django 3.0.5 on 2021-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='document',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
