# Generated by Django 3.0.5 on 2021-01-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210124_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='document',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
