# Generated by Django 3.0.5 on 2021-01-24 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210124_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='document',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
