# Generated by Django 3.0.5 on 2021-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210124_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='document',
            field=models.FileField(upload_to='images/'),
        ),
    ]
