# Generated by Django 3.0.5 on 2021-01-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210125_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='document',
            field=models.ImageField(upload_to='images'),
        ),
    ]
