# Generated by Django 3.0.5 on 2021-01-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210125_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='document',
            field=models.FileField(upload_to='media/images'),
        ),
    ]
