# Generated by Django 3.0.5 on 2021-01-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210125_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='sharable',
            field=models.IntegerField(default=0),
        ),
    ]
